version: '2'
services:
   rabbitmq:
      image: rabbitmq:3
      container_name: rabbitmq
   database:
      build: ./postgres
      container_name: database
      environment:
         - PGPASSWORD=docker
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=kitdm20
   base-repo:
      build: ./base-repo
      container_name: base-repo
      ports: 
        - "8080:8080"
      volumes:
        - ./data:/var/repository
      links:
        - database
        - rabbitmq
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq
        - BASE-REPO_PORT_8080_TCP_ADDR=base-repo
        - ADMIN-SERVICE_PORT_8060_TCP_ADDR=admin-service
   collection-api:
      build: ./collection-api
      container_name: collection-api
      ports: 
        - "8070:8070"
      links:
        - database
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq
        - ADMIN-SERVICE_PORT_8060_TCP_ADDR=admin-service 
        - COLLECTION-API_PORT_8070_TCP_ADDR=collection-api
   admin-service:
      build: ./admin-service
      container_name: admin-service
      ports: 
        - "8060:8060"
      links:
        - database
        - base-repo
        - collection-api
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - BASE-REPO_PORT_8080_TCP_ADDR=base-repo
        - COLLECTION-API_PORT_8070_TCP_ADDR=collection-api
