version: '2'
services:
   rabbitmq:
      image: rabbitmq:3
      container_name: rabbitmq
   elastic:
      image: elasticsearch:7.17.8
      container_name: elastic
      environment:
        - discovery.type=single-node
        - logger.org.elasticsearch=ERROR
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - "9200:9200"
        - "9300:9300"
      ulimits:
        memlock:
         soft: -1
         hard: -1
      volumes:
        - ./elastic-data:/usr/share/elasticsearch/data
        - ./elastic/etc/sysctl.conf:/etc/sysctl.conf
   database:
      build: ./postgres
      container_name: database
      environment:
         - PGPASSWORD=docker
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=kitdm20
   base-repo:
      build: ./base-repo
      container_name: base-repo
      ports: 
        - "8080:8080"
      volumes:
        - ./data:/var/repository
        - ./base-repo:/opt/base-repo
      links:
        - database
        - rabbitmq
        - elastic
        - admin-service
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq
        - ELASTIC_PORT_9200_TCP_ADDR=elastic
        - BASE-REPO_PORT_8080_TCP_ADDR=base-repo
        - ADMIN-SERVICE_PORT_8060_TCP_ADDR=admin-service
   admin-service:
      build: ./admin-service
      container_name: admin-service
      ports: 
        - "8060:8060"
      volumes:
        - ./admin-service:/opt/admin-service
      links:
        - database
        - rabbitmq
        - elastic
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq
        - ELASTIC_PORT_9200_TCP_ADDR=elastic
   gateway:
      build: ./gateway
      container_name: gateway
      ports:
        - "8010:8010"
      volumes:
        - ./gateway:/opt/gateway
      links:
        - base-repo
        - admin-service
      environment:
        - BASE-REPO_PORT_8080_TCP_ADDR=base-repo 
        - ADMIN-SERVICE_PORT_8060_TCP_ADDR=admin-service
